/**
 * FlowState — supabase.js
 * Supabase client init, auth helpers, and data sync layer.
 * Loaded before main.js on every page via <script> tag.
 *
 * ENV VARS injected at build time by Vercel (see vercel.json / env setup):
 *   SUPABASE_URL       → window.__ENV.SUPABASE_URL
 *   SUPABASE_ANON_KEY  → window.__ENV.SUPABASE_ANON_KEY
 *
 * The env.js file (generated by /api/env.js serverless function) exposes
 * only the anon key — never the service_role key.
 */

// ── Supabase CDN client (loaded via <script> in HTML head)
// <script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/dist/umd/supabase.min.js"></script>

const _supa = (() => {
  const url = window.__ENV?.SUPABASE_URL;
  const key = window.__ENV?.SUPABASE_ANON_KEY;
  if (!url || !key) {
    console.warn('[FlowState] Supabase env vars missing. Running in offline mode.');
    return null;
  }
  return window.supabase.createClient(url, key, {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,   // handles magic link + OAuth redirects
      storageKey: 'flowstate_auth'
    }
  });
})();

/* ─── AUTH STATE ──────────────────────────────────────────── */

const Auth = {
  /** Current Supabase user object or null */
  user: null,

  async init() {
    if (!_supa) return;
    const { data: { session } } = await _supa.auth.getSession();
    this.user = session?.user ?? null;

    // Listen for sign-in / sign-out events
    _supa.auth.onAuthStateChange(async (event, session) => {
      this.user = session?.user ?? null;

      if (event === 'SIGNED_IN') {
        await Sync.pull();           // load user data from Supabase on login
        Profile.init();
        Toast.show('Sessão iniciada ✓', 'success');
      }

      if (event === 'SIGNED_OUT') {
        Store.clear();               // wipe local cache on logout
        window.location.href = _rootPath() + 'pages/login.html';
      }

      if (event === 'TOKEN_REFRESHED') {
        // Silent — token was auto-refreshed
      }
    });

    // If not authenticated, redirect to login (except on login page itself)
    if (!this.user && !window.location.pathname.includes('login')) {
      window.location.href = _rootPath() + 'pages/login.html';
    }

    if (this.user) {
      await Sync.pull();
    }
  },

  async signUp(email, password) {
    if (!_supa) return { error: { message: 'Supabase não configurado' } };
    return _supa.auth.signUp({ email, password });
  },

  async signIn(email, password) {
    if (!_supa) return { error: { message: 'Supabase não configurado' } };
    return _supa.auth.signInWithPassword({ email, password });
  },

  async signInWithGoogle() {
    if (!_supa) return;
    return _supa.auth.signInWithOAuth({
      provider: 'google',
      options: { redirectTo: window.location.origin + _rootPath() + 'index.html' }
    });
  },

  async signOut() {
    if (!_supa) return;
    await _supa.auth.signOut();
  },

  get uid() { return this.user?.id ?? null; },
  get email() { return this.user?.email ?? null; }
};

/* ─── SYNC LAYER ──────────────────────────────────────────── */

/**
 * Sync strategy:
 *  - pull()  → Supabase → localStorage (on login / page load)
 *  - push*() → localStorage → Supabase (after every local mutation)
 *  - Conflict resolution: last-write-wins via updated_at / upsert
 */
const Sync = {

  /** Pull all user data from Supabase into localStorage */
  async pull() {
    if (!_supa || !Auth.uid) return;
    try {
      const [tasks, schedule, settings, stats, sessions] = await Promise.all([
        _supa.from('tasks').select('*').eq('user_id', Auth.uid).order('created_at', { ascending: false }),
        _supa.from('schedule').select('*').eq('user_id', Auth.uid),
        _supa.from('settings').select('*').eq('user_id', Auth.uid).single(),
        _supa.from('stats').select('*').eq('user_id', Auth.uid).order('date', { ascending: false }).limit(90),
        _supa.from('pomo_sessions').select('*').eq('user_id', Auth.uid).order('started_at', { ascending: false }).limit(500),
      ]);

      // Tasks: map DB columns → client shape
      if (tasks.data?.length) {
        const mapped = tasks.data.map(dbTaskToClient);
        Store.set('tasks', mapped);
      }

      // Schedule: map DB columns → client shape
      if (schedule.data?.length) {
        const mapped = schedule.data.map(dbScheduleToClient);
        Store.set('schedule', mapped);
      }

      // Settings
      if (settings.data) {
        const s = settings.data;
        Store.set('settings', {
          username:    s.username,
          avatar:      s.avatar,
          theme:       s.theme,
          customColors:s.custom_colors,
          pomodoroFocus:  s.pomodoro?.focus  ?? 25,
          pomodoroShort:  s.pomodoro?.short  ?? 5,
          pomodoroLong:   s.pomodoro?.long   ?? 15,
          pomodoroCycles: s.pomodoro?.cycles ?? 4,
          pomodoroNotify: s.pomodoro?.notify ?? true,
          pomodoroSound:  s.pomodoro?.sound  ?? true,
          dailyGoals:  s.daily_goals
        });
      }

      // Stats: store each day individually
      if (stats.data?.length) {
        stats.data.forEach(row => {
          Store.set('stats_' + row.date, {
            focusSeconds:   row.focus_seconds,
            tasksCompleted: row.tasks_done,
            pomoCycles:     row.pomo_cycles
          });
        });
      }

      // Pomo sessions
      if (sessions.data?.length) {
        const mapped = sessions.data.map(r => ({
          mode:            r.mode,
          startedAt:       r.started_at,
          durationSeconds: r.duration_seconds
        }));
        Store.set('pomo_sessions', mapped);
      }

    } catch (err) {
      console.error('[Sync.pull]', err);
    }
  },

  /* ── TASKS ── */
  async pushTask(task) {
    if (!_supa || !Auth.uid) return;
    const row = clientTaskToDb(task, Auth.uid);
    const { error } = await _supa.from('tasks').upsert(row, { onConflict: 'id' });
    if (error) console.error('[Sync.pushTask]', error);
  },

  async deleteTask(id) {
    if (!_supa || !Auth.uid) return;
    const { error } = await _supa.from('tasks').delete().eq('id', id).eq('user_id', Auth.uid);
    if (error) console.error('[Sync.deleteTask]', error);
  },

  /* ── SCHEDULE ── */
  async pushScheduleEvent(ev) {
    if (!_supa || !Auth.uid) return;
    const row = clientScheduleToDb(ev, Auth.uid);
    const { error } = await _supa.from('schedule').upsert(row, { onConflict: 'id' });
    if (error) console.error('[Sync.pushScheduleEvent]', error);
  },

  async deleteScheduleEvent(id) {
    if (!_supa || !Auth.uid) return;
    const { error } = await _supa.from('schedule').delete().eq('id', id).eq('user_id', Auth.uid);
    if (error) console.error('[Sync.deleteScheduleEvent]', error);
  },

  /* ── SETTINGS ── */
  async pushSettings(settings) {
    if (!_supa || !Auth.uid) return;
    const row = {
      user_id:      Auth.uid,
      username:     settings.username,
      avatar:       settings.avatar,
      theme:        settings.theme,
      custom_colors:settings.customColors || {},
      pomodoro: {
        focus:  settings.pomodoroFocus,
        short:  settings.pomodoroShort,
        long:   settings.pomodoroLong,
        cycles: settings.pomodoroCycles,
        notify: settings.pomodoroNotify,
        sound:  settings.pomodoroSound
      },
      daily_goals: settings.dailyGoals
    };
    const { error } = await _supa.from('settings').upsert(row, { onConflict: 'user_id' });
    if (error) console.error('[Sync.pushSettings]', error);
  },

  /* ── STATS ── */
  async pushStats(date, stats) {
    if (!_supa || !Auth.uid) return;
    const { error } = await _supa.from('stats').upsert({
      user_id:       Auth.uid,
      date,
      focus_seconds: stats.focusSeconds  || 0,
      tasks_done:    stats.tasksCompleted|| 0,
      pomo_cycles:   stats.pomoCycles    || 0
    }, { onConflict: 'user_id,date' });
    if (error) console.error('[Sync.pushStats]', error);
  },

  /* ── POMO SESSION ── */
  async pushPomoSession(session) {
    if (!_supa || !Auth.uid) return;
    const { error } = await _supa.from('pomo_sessions').insert({
      user_id:          Auth.uid,
      mode:             session.mode,
      started_at:       session.startedAt,
      duration_seconds: session.durationSeconds
    });
    if (error) console.error('[Sync.pushPomoSession]', error);
  },

  /* ── FULL PUSH (export current localStorage → Supabase) ── */
  async pushAll() {
    if (!_supa || !Auth.uid) return;
    const tasks    = Store.get('tasks', []);
    const schedule = Store.get('schedule', []);
    const settings = Store.get('settings', {});

    await Promise.all([
      ...tasks.map(t => this.pushTask(t)),
      ...schedule.map(e => this.pushScheduleEvent(e)),
      this.pushSettings(settings)
    ]);

    Toast.show('Dados sincronizados ✓', 'success');
  }
};

/* ─── DB ↔ CLIENT MAPPERS ────────────────────────────────── */

function clientTaskToDb(task, userId) {
  return {
    id:             task.id,
    user_id:        userId,
    text:           task.text,
    note:           task.note          || '',
    priority:       task.priority      || 'medium',
    category:       task.category      || 'personal',
    due:            task.due           || '',
    done:           task.done          || false,
    created_at:     task.createdAt     || new Date().toISOString(),
    done_at:        task.doneAt        || null,
    recurring_type: task.recurringType || null,
    recurring_days: task.recurringDays || null,
    recurring_day:  task.recurringDay  || null
  };
}

function dbTaskToClient(row) {
  return {
    id:            row.id,
    text:          row.text,
    note:          row.note          || '',
    priority:      row.priority,
    category:      row.category,
    due:           row.due           || '',
    done:          row.done,
    createdAt:     row.created_at,
    doneAt:        row.done_at       || null,
    recurringType: row.recurring_type|| null,
    recurringDays: row.recurring_days|| null,
    recurringDay:  row.recurring_day || null
  };
}

function clientScheduleToDb(ev, userId) {
  return {
    id:         ev.id,
    user_id:    userId,
    title:      ev.title,
    category:   ev.category || 'other',
    color:      ev.color    || '#6ee7b7',
    start_time: ev.start,
    end_time:   ev.end,
    days:       ev.days     || [0,1,2,3,4,5,6]
  };
}

function dbScheduleToClient(row) {
  return {
    id:       row.id,
    title:    row.title,
    category: row.category,
    color:    row.color,
    start:    row.start_time,
    end:      row.end_time,
    days:     row.days
  };
}

/* ─── UTILITY ─────────────────────────────────────────────── */

function _rootPath() {
  // Works whether deployed at root or in a subdir
  const p = window.location.pathname;
  if (p.includes('/pages/')) return p.split('/pages/')[0] + '/';
  return p.endsWith('/') ? p : p.split('/').slice(0, -1).join('/') + '/';
}

/* ─── PATCH Store.set TO AUTO-SYNC ───────────────────────── */
// Intercept writes to specific keys and push to Supabase immediately.
// This keeps existing todo.js / schedule.js / settings.js code unchanged.

const _originalSet = Store.set.bind(Store);
Store.set = function(key, value) {
  _originalSet(key, value);              // always write localStorage first
  if (!_supa || !Auth.uid) return;       // skip if offline or not authed

  // Debounced push per key type
  clearTimeout(Store._syncTimers?.[key]);
  Store._syncTimers = Store._syncTimers || {};
  Store._syncTimers[key] = setTimeout(async () => {
    if (key === 'tasks') {
      // Push entire tasks array as upsert batch
      const tasks = value;
      if (Array.isArray(tasks)) {
        // Delete-all-then-insert is risky. Use individual upserts instead.
        // For bulk efficiency on large lists use a single upsert call:
        const rows = tasks.map(t => clientTaskToDb(t, Auth.uid));
        if (rows.length) {
          const { error } = await _supa.from('tasks').upsert(rows, { onConflict: 'id' });
          if (error) console.error('[Store.set → tasks]', error);
        }
      }
    } else if (key === 'schedule') {
      const rows = (value || []).map(e => clientScheduleToDb(e, Auth.uid));
      if (rows.length) {
        const { error } = await _supa.from('schedule').upsert(rows, { onConflict: 'id' });
        if (error) console.error('[Store.set → schedule]', error);
      }
    } else if (key === 'settings') {
      await Sync.pushSettings(value);
    } else if (key.startsWith('stats_')) {
      const date = key.replace('stats_', '');
      await Sync.pushStats(date, value);
    } else if (key === 'pomo_sessions') {
      // Only push the last session (newest append)
      const sessions = value;
      if (Array.isArray(sessions) && sessions.length) {
        await Sync.pushPomoSession(sessions[sessions.length - 1]);
      }
    }
  }, 800); // 800ms debounce — batches rapid successive writes
};
